### ISSUE TITLE
fullscreen support

### ISSUE THREAD

**Issue by Lewiscowles1986** [thisarray/jsgame0#1]
I wonder if this would work, or if you would be interested in full-screen support. 

I just used `element.requestFullscreen()` where `element` was set to `document.getElementById('screen')`

Native browser support should be detected and if available, maybe ui surfaced, like the `pause`. `<Esc>` key exits fullscreen on my mac, linux and windows, but happy to hear if there would be blockers, or you are not interested, or would rather add what is virtually a one-liner yourself.

Very cool little library, I was actually searching the internet to try to find if anyone has refactored the examples given, and it seems several people have.

**Comment by thisarray** [comment]
Pygame Zero does not have a fullscreen so I have not seen a use case for fullscreen.

The beauty of jsgame0.js being a very thin library is that you can do this on your own.

The following code adds a `on_key_down()` function to toggle fullscreen with any key press.

```js
/*
 * The #screen element.
 *
 * Cannot name it "screen" due to the screen global.
 */
const gameScreen = document.querySelector('#screen');

if (gameScreen.requestFullscreen) {
  // If Fullscreen API is supported on the browser
  function on_key_down(key) {
    if (document.fullscreenElement == null) {
      // If no element is currently being displayed fullscreen
      gameScreen.requestFullscreen();
    }
    else {
      // Otherwise, currently in fullscreen mode
      document.exitFullscreen();
    }
  }
}
```

You can find a full example in tests/test_fullscreen.html.

To map it to a specific key, just check if `key` matches a `keys` enumeration like `if (key === keys.SPACE)`.
I warn against using the ESC key because browsers intercept it to exit fullscreen.
In addition, the mouse positioning will be off due to scaling.
