### ISSUE TITLE
Paused game, seems not to pause audio

### ISSUE THREAD

**Issue by Lewiscowles1986** [thisarray/jsgame0#2]
Wondering if an interesting difference might be ambient sound, versus state-specific sound, but when I pause, this thing keeps making noise. Not sure if mute is an idea, or a config for mute on pause could or should be added to the engine.

I sort-of hacked something naughty together, which I am sure is wrong

`[...document.querySelectorAll('audio')].forEach(async (elem) => await elem.pause())`

It seems unpausing automatically schedules all the sounds I would want, so I don't know if this is too blunt an instrument but it seems to work for me.

**Comment by thisarray** [comment]
Nice catch. This is completely my bad.
When Pause is clicked, the code pauses the music but lets sounds run to completion because sounds are generally short and do not loop.

Where did you notice this issue?
Was it Infinite Bunner or Substitute Soccer?
I aim to be extremely faithful to the original Python code in JavaScript ports down to the infinitely looping sounds.

**Comment by Lewiscowles1986** [comment]
Infinite Bunner and Substitute soccer both did this and if it wasn't a loop, it was a very long soundtrack.

I was under the impression the pause button, was Pause game, not enter pause game-state. It's not that I think all games should be silent if it's a pause menu (gamestate). Perhaps more that the audio from one game-state should not bleed into another.

I'd also not attempted to stay true to pygame implementation with this comment.

**Comment by thisarray** [comment]
If those are the culprits, then I think I fixed it.
